[2021-07-29 00:30:19 +0000] [21369] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:30:19 +0000] [21369] [INFO] Listening at: http://0.0.0.0:8000 (21369)
[2021-07-29 00:30:19 +0000] [21369] [INFO] Using worker: sync
[2021-07-29 00:30:19 +0000] [21370] [INFO] Booting worker with pid: 21370
[2021-07-29 00:30:19 +0000] [21370] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'metgo_test'
[2021-07-29 00:30:19 +0000] [21370] [INFO] Worker exiting (pid: 21370)
[2021-07-29 00:30:19 +0000] [21369] [INFO] Shutting down: Master
[2021-07-29 00:30:19 +0000] [21369] [INFO] Reason: Worker failed to boot.
[2021-07-29 00:32:06 +0000] [21375] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:32:06 +0000] [21375] [INFO] Listening at: http://0.0.0.0:8000 (21375)
[2021-07-29 00:32:06 +0000] [21375] [INFO] Using worker: sync
[2021-07-29 00:32:06 +0000] [21376] [INFO] Booting worker with pid: 21376
[2021-07-29 00:32:06 +0000] [21376] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'metgo_test'
[2021-07-29 00:32:06 +0000] [21376] [INFO] Worker exiting (pid: 21376)
[2021-07-29 00:32:06 +0000] [21375] [INFO] Shutting down: Master
[2021-07-29 00:32:06 +0000] [21375] [INFO] Reason: Worker failed to boot.
[2021-07-29 00:32:18 +0000] [21377] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:32:18 +0000] [21377] [INFO] Listening at: http://0.0.0.0:8000 (21377)
[2021-07-29 00:32:18 +0000] [21377] [INFO] Using worker: sync
[2021-07-29 00:32:18 +0000] [21378] [INFO] Booting worker with pid: 21378
[2021-07-29 00:32:18 +0000] [21378] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/settings.py", line 3, in <module>
    from my_settings import DATABASES, SECRET_KEY
  File "/home/ubuntu/wecode/metgo_test/my_settings.py", line 7
    'HOST': 'project-database.csoj9lvubxzw.ap-northeast-2.rds.amazonaws.com",
                                                                             ^
SyntaxError: EOL while scanning string literal
[2021-07-29 00:32:18 +0000] [21378] [INFO] Worker exiting (pid: 21378)
[2021-07-29 00:32:18 +0000] [21377] [INFO] Shutting down: Master
[2021-07-29 00:32:18 +0000] [21377] [INFO] Reason: Worker failed to boot.
[2021-07-29 00:32:44 +0000] [21384] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:32:44 +0000] [21384] [INFO] Listening at: http://0.0.0.0:8000 (21384)
[2021-07-29 00:32:44 +0000] [21384] [INFO] Using worker: sync
[2021-07-29 00:32:44 +0000] [21385] [INFO] Booting worker with pid: 21385
[2021-07-29 00:32:44 +0000] [21385] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/settings.py", line 3, in <module>
    from my_settings import DATABASES, SECRET_KEY
  File "/home/ubuntu/wecode/metgo_test/my_settings.py", line 7
    'HOST': 'project-database.csoj9lvubxzw.ap-northeast-2.rds.amazonaws.com",
                                                                             ^
SyntaxError: EOL while scanning string literal
[2021-07-29 00:32:44 +0000] [21385] [INFO] Worker exiting (pid: 21385)
[2021-07-29 00:32:44 +0000] [21384] [INFO] Shutting down: Master
[2021-07-29 00:32:44 +0000] [21384] [INFO] Reason: Worker failed to boot.
[2021-07-29 00:33:18 +0000] [21396] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:33:18 +0000] [21396] [INFO] Listening at: http://0.0.0.0:8000 (21396)
[2021-07-29 00:33:18 +0000] [21396] [INFO] Using worker: sync
[2021-07-29 00:33:18 +0000] [21397] [INFO] Booting worker with pid: 21397
Internal Server Error: /masters/signup
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/urls.py", line 10, in <module>
    path('masters', include('masters.urls')),
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/masters/urls.py", line 3, in <module>
    from masters.views import MasterSignupView, MasterSigninView, KakaoSigninView, MasterView
  File "/home/ubuntu/wecode/metgo_test/masters/views.py", line 18, in <module>
    from core.views     import master_signin_check, AWSAPI
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 2, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
Internal Server Error: /masters/signup
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'metGo_test'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/masters/views.py", line 40, in post
    if Master.objects.filter(email=email).exists():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 552, in has_results
    return compiler.has_results()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1049, "Unknown database 'metGo_test'")
Internal Server Error: /masters/signup
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'metGo_test'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/masters/views.py", line 40, in post
    if Master.objects.filter(email=email).exists():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 552, in has_results
    return compiler.has_results()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1049, "Unknown database 'metGo_test'")
[2021-07-29 00:35:22 +0000] [21396] [INFO] Handling signal: term
[2021-07-29 00:35:22 +0000] [21397] [INFO] Worker exiting (pid: 21397)
[2021-07-29 00:35:22 +0000] [21396] [INFO] Shutting down: Master
[2021-07-29 00:55:21 +0000] [21480] [INFO] Starting gunicorn 20.1.0
[2021-07-29 00:55:21 +0000] [21480] [INFO] Listening at: http://0.0.0.0:8000 (21480)
[2021-07-29 00:55:21 +0000] [21480] [INFO] Using worker: sync
[2021-07-29 00:55:21 +0000] [21481] [INFO] Booting worker with pid: 21481
2021-07-29 00:55:25,454 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 00:55:25,454 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:55:25,455 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'ecardenas@gmail.com' LIMIT 21; args=('ecardenas@gmail.com',)
2021-07-29 00:55:53,066 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:55:53,067 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 00:55:53,069 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 00:55:53,071 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 00:55:53,075 DEBUG (0.003) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` WHERE (`applications`.`user_id` = 32 AND `applications`.`service_id` = 1) LIMIT 21; args=(32, 1)
2021-07-29 00:55:53,079 DEBUG (0.003) INSERT INTO `quotations` (`created_at`, `updated_at`, `application_id`, `price`, `is_completed`, `master_id`) VALUES ('2021-07-29 00:55:53.076420', '2021-07-29 00:55:53.076466', 3, NULL, 0, 3); args=['2021-07-29 00:55:53.076420', '2021-07-29 00:55:53.076466', 3, None, False, 3]
2021-07-29 00:55:56,450 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:55:56,451 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 00:55:56,453 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 226 LIMIT 21; args=(226,)
2021-07-29 00:55:56,454 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 00:55:56,456 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` WHERE (`applications`.`user_id` = 32 AND `applications`.`service_id` = 3) LIMIT 21; args=(32, 3)
2021-07-29 00:55:56,459 DEBUG (0.002) INSERT INTO `quotations` (`created_at`, `updated_at`, `application_id`, `price`, `is_completed`, `master_id`) VALUES ('2021-07-29 00:55:56.456790', '2021-07-29 00:55:56.456828', 1, NULL, 0, 226); args=['2021-07-29 00:55:56.456790', '2021-07-29 00:55:56.456828', 1, None, False, 226]
2021-07-29 00:56:28,976 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:56:28,977 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 00:56:28,980 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id`, `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `quotations` INNER JOIN `applications` ON (`quotations`.`application_id` = `applications`.`id`) WHERE `quotations`.`master_id` = 1; args=(1,)
2021-07-29 00:58:39,484 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:58:39,485 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`email` = 'patrickjackson@perry.info' LIMIT 21; args=('patrickjackson@perry.info',)
2021-07-29 00:58:52,730 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 00:58:52,731 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 00:58:52,733 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id`, `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `quotations` INNER JOIN `applications` ON (`quotations`.`application_id` = `applications`.`id`) WHERE `quotations`.`master_id` = 215; args=(215,)
2021-07-29 00:58:52,735 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:00:55,041 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:00:55,042 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:00:55,046 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:01,735 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:01,736 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:01,740 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:05,836 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:05,837 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:05,840 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:07,454 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:07,455 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:07,459 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:08,295 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:08,297 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:08,300 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:09,035 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:09,036 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:09,040 DEBUG (0.003) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:27,069 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:27,070 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
Internal Server Error: /quotations
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 32, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 37, in patch
    data         = json.loads(request.body)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 20 (char 45)
2021-07-29 01:01:34,808 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:34,809 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:34,811 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` WHERE `quotations`.`id` = 742 LIMIT 21; args=(742,)
2021-07-29 01:01:34,815 DEBUG (0.004) DELETE FROM `quotations` WHERE `quotations`.`id` IN (742); args=(742,)
2021-07-29 01:01:35,452 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:35,453 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:35,455 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` WHERE `quotations`.`id` = 742 LIMIT 21; args=(742,)
2021-07-29 01:01:35,466 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` LIMIT 21; args=()
Internal Server Error: /quotations
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 32, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 42, in patch
    Quotation.objects.get(id=quotation_id).delete()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
quotations.models.Quotation.DoesNotExist: Quotation matching query does not exist.
2021-07-29 01:01:39,893 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:39,894 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:39,895 DEBUG (0.001) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:46,293 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:46,294 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:46,296 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` WHERE `quotations`.`id` = 742 LIMIT 21; args=(742,)
2021-07-29 01:01:46,306 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` LIMIT 21; args=()
Internal Server Error: /quotations
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 32, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 42, in patch
    Quotation.objects.get(id=quotation_id).delete()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
quotations.models.Quotation.DoesNotExist: Quotation matching query does not exist.
2021-07-29 01:01:48,943 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:48,944 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:48,945 DEBUG (0.001) UPDATE `quotations` SET `is_completed` = 1 WHERE `quotations`.`id` = 742; args=(True, 742)
2021-07-29 01:01:51,927 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:01:51,928 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE `masters`.`id` = 215 LIMIT 21; args=(215,)
2021-07-29 01:01:51,929 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` WHERE `quotations`.`id` = 742 LIMIT 21; args=(742,)
2021-07-29 01:01:51,939 DEBUG (0.001) SELECT `quotations`.`id`, `quotations`.`created_at`, `quotations`.`updated_at`, `quotations`.`application_id`, `quotations`.`price`, `quotations`.`is_completed`, `quotations`.`master_id` FROM `quotations` LIMIT 21; args=()
Internal Server Error: /quotations
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 32, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 42, in patch
    Quotation.objects.get(id=quotation_id).delete()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
quotations.models.Quotation.DoesNotExist: Quotation matching query does not exist.
2021-07-29 01:03:50,499 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:03:50,501 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:03:50,502 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`name` = '중구' LIMIT 21; args=('중구',)
Not Found: /applications
2021-07-29 01:04:00,357 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:04:00,358 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:04:00,359 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`name` = '중구' LIMIT 21; args=('중구',)
Not Found: /applications
2021-07-29 01:04:17,681 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:04:17,682 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:04:17,684 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`name` = '중구' LIMIT 21; args=('중구',)
2021-07-29 01:04:17,686 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21 FOR UPDATE; args=(4, 32)
2021-07-29 01:04:17,689 DEBUG (0.001) SAVEPOINT `s140196332970176_x1`; args=None
2021-07-29 01:04:17,690 DEBUG (0.001) ROLLBACK TO SAVEPOINT `s140196332970176_x1`; args=None
2021-07-29 01:04:17,690 DEBUG (0.000) RELEASE SAVEPOINT `s140196332970176_x1`; args=None
2021-07-29 01:04:17,715 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` LIMIT 21; args=()
2021-07-29 01:04:17,719 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` LIMIT 21; args=()
Internal Server Error: /applications
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
applications.models.Application.DoesNotExist: Application matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'User'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 18, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/applications/views.py", line 23, in post
    Application.objects.update_or_create(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/related.py", line 971, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2486, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <User: User object (32)>.
[2021-07-29 01:05:10 +0000] [21480] [INFO] Handling signal: term
[2021-07-29 01:05:10 +0000] [21481] [INFO] Worker exiting (pid: 21481)
[2021-07-29 01:05:11 +0000] [21480] [INFO] Shutting down: Master
[2021-07-29 01:05:13 +0000] [21506] [INFO] Starting gunicorn 20.1.0
[2021-07-29 01:05:13 +0000] [21506] [INFO] Listening at: http://0.0.0.0:8000 (21506)
[2021-07-29 01:05:13 +0000] [21506] [INFO] Using worker: sync
[2021-07-29 01:05:13 +0000] [21507] [INFO] Booting worker with pid: 21507
2021-07-29 01:05:17,349 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 01:05:17,349 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:05:17,350 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:05:17,353 DEBUG (0.002) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`name` = '중구' LIMIT 21; args=('중구',)
2021-07-29 01:05:17,356 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21 FOR UPDATE; args=(4, 32)
2021-07-29 01:05:17,357 DEBUG (0.001) SAVEPOINT `s140539965300928_x1`; args=None
2021-07-29 01:05:17,359 DEBUG (0.001) INSERT INTO `applications` (`created_at`, `updated_at`, `age`, `region_id`, `career`, `gender`, `user_id`, `service_id`) VALUES ('2021-07-29 01:05:17.358391', '2021-07-29 01:05:17.358435', 10, 2, 10, 'male', 32, 4); args=['2021-07-29 01:05:17.358391', '2021-07-29 01:05:17.358435', 10, 2, 10, 'male', 32, 4]
2021-07-29 01:05:17,359 DEBUG (0.001) RELEASE SAVEPOINT `s140539965300928_x1`; args=None
Bad Request: /applications/services/4/masters
2021-07-29 01:08:16,691 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:08:16,692 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:08:16,695 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id`, `services`.`id`, `services`.`name`, `services`.`category_id` FROM `applications` INNER JOIN `services` ON (`applications`.`service_id` = `services`.`id`) WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21; args=(4, 32)
2021-07-29 01:08:16,696 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 01:08:16,700 DEBUG (0.002) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE (`masters`.`main_service_id` = 4 AND `masters`.`gender` = 'male' AND `masters`.`region_id` = 2 AND `masters`.`birth` BETWEEN '2001-07-29' AND '2011-07-29' AND `masters`.`career` BETWEEN 10 AND 15); args=(4, 'male', 2, '2001-07-29', '2011-07-29', 10, 15)
2021-07-29 01:08:16,701 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 186; args=(186,)
2021-07-29 01:08:16,703 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 186; args=(186,)
2021-07-29 01:08:16,704 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 399; args=(399,)
2021-07-29 01:08:16,706 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 399; args=(399,)
2021-07-29 01:08:16,707 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 575; args=(575,)
2021-07-29 01:08:16,708 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 575; args=(575,)
2021-07-29 01:08:46,235 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:08:46,236 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:08:46,239 DEBUG (0.002) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id`, `services`.`id`, `services`.`name`, `services`.`category_id` FROM `applications` INNER JOIN `services` ON (`applications`.`service_id` = `services`.`id`) WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21; args=(4, 32)
2021-07-29 01:08:46,241 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 01:08:46,243 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE (`masters`.`main_service_id` = 4 AND `masters`.`gender` = 'male' AND `masters`.`region_id` = 2 AND `masters`.`birth` BETWEEN '2001-07-29' AND '2011-07-29' AND `masters`.`career` BETWEEN 10 AND 15); args=(4, 'male', 2, '2001-07-29', '2011-07-29', 10, 15)
2021-07-29 01:08:46,245 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 186; args=(186,)
2021-07-29 01:08:46,246 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 186; args=(186,)
2021-07-29 01:08:46,248 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 399; args=(399,)
2021-07-29 01:08:46,249 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 399; args=(399,)
2021-07-29 01:08:46,250 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 575; args=(575,)
2021-07-29 01:08:46,252 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 575; args=(575,)
2021-07-29 01:09:44,217 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:09:44,218 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:09:44,219 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`name` = '용산구' LIMIT 21; args=('용산구',)
2021-07-29 01:09:44,221 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id` FROM `applications` WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21 FOR UPDATE; args=(4, 32)
2021-07-29 01:09:44,223 DEBUG (0.001) UPDATE `applications` SET `created_at` = '2021-07-29 01:05:17.358391', `updated_at` = '2021-07-29 01:09:44.222267', `age` = 5, `region_id` = 3, `career` = 5, `gender` = 'female', `user_id` = 32, `service_id` = 4 WHERE `applications`.`id` = 20; args=('2021-07-29 01:05:17.358391', '2021-07-29 01:09:44.222267', 5, 3, 5, 'female', 32, 4, 20)
2021-07-29 01:09:49,031 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:09:49,032 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:09:49,034 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id`, `services`.`id`, `services`.`name`, `services`.`category_id` FROM `applications` INNER JOIN `services` ON (`applications`.`service_id` = `services`.`id`) WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21; args=(4, 32)
2021-07-29 01:09:49,036 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 01:09:49,038 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE (`masters`.`main_service_id` = 4 AND `masters`.`gender` = 'female' AND `masters`.`region_id` = 3 AND `masters`.`birth` BETWEEN '2006-07-29' AND '2016-07-29' AND `masters`.`career` BETWEEN 5 AND 10); args=(4, 'female', 3, '2006-07-29', '2016-07-29', 5, 10)
2021-07-29 01:09:49,040 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 01:09:49,042 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 01:09:49,043 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
2021-07-29 01:09:49,044 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
[2021-07-29 01:10:16 +0000] [21506] [INFO] Handling signal: term
[2021-07-29 01:10:16 +0000] [21507] [INFO] Worker exiting (pid: 21507)
[2021-07-29 01:10:16 +0000] [21506] [INFO] Shutting down: Master
[2021-07-29 01:13:46 +0000] [21595] [INFO] Starting gunicorn 20.1.0
[2021-07-29 01:13:46 +0000] [21595] [INFO] Listening at: http://0.0.0.0:8000 (21595)
[2021-07-29 01:13:46 +0000] [21595] [INFO] Using worker: sync
[2021-07-29 01:13:46 +0000] [21596] [INFO] Booting worker with pid: 21596
2021-07-29 01:13:49,497 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 01:13:49,498 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:13:49,498 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 01:13:49,501 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id`, `services`.`id`, `services`.`name`, `services`.`category_id` FROM `applications` INNER JOIN `services` ON (`applications`.`service_id` = `services`.`id`) WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21; args=(4, 32)
2021-07-29 01:13:49,503 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 01:13:49,506 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE (`masters`.`main_service_id` = 4 AND `masters`.`gender` = 'female' AND `masters`.`region_id` = 3 AND `masters`.`birth` BETWEEN '2006-07-29' AND '2016-07-29' AND `masters`.`career` BETWEEN 5 AND 10); args=(4, 'female', 3, '2006-07-29', '2016-07-29', 5, 10)
2021-07-29 01:13:49,508 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 01:13:49,509 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 01:13:49,510 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
2021-07-29 01:13:49,512 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
Not Found: /apikey
2021-07-29 01:33:36,799 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:33:36,800 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:33:36,801 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:33:36,802 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:33:36,803 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:33:36,805 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
Internal Server Error: /services/y
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'y'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'y'.
2021-07-29 01:34:02,786 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:34:02,788 DEBUG (0.002) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:02,790 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:02,791 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:02,792 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:02,794 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
Internal Server Error: /services/y
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'y'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'y'.
2021-07-29 01:34:04,280 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:34:04,281 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:04,282 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:04,283 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:04,285 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
2021-07-29 01:34:04,286 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` LIMIT 21; args=()
Internal Server Error: /services/y
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'y'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'y'.
Unauthorized: /users/signup
Not Found: /1
Not Found: /4
2021-07-29 01:35:25,839 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:35:25,840 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'tjdwjdwns@naver.com' LIMIT 21; args=('tjdwjdwns@naver.com',)
Bad Request: /users/signin
Not Found: /1
2021-07-29 01:37:01,892 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:37:01,893 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'ecardenas@gmail.com' LIMIT 21; args=('ecardenas@gmail.com',)
Not Found: /categories
[2021-07-29 01:44:10 +0000] [21595] [INFO] Handling signal: term
[2021-07-29 01:44:10 +0000] [21596] [INFO] Worker exiting (pid: 21596)
[2021-07-29 01:44:10 +0000] [21595] [INFO] Shutting down: Master
[2021-07-29 01:44:22 +0000] [22251] [INFO] Starting gunicorn 20.1.0
[2021-07-29 01:44:22 +0000] [22251] [INFO] Listening at: http://0.0.0.0:8000 (22251)
[2021-07-29 01:44:22 +0000] [22251] [INFO] Using worker: sync
[2021-07-29 01:44:22 +0000] [22252] [INFO] Booting worker with pid: 22252
2021-07-29 01:44:35,018 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 01:44:35,019 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:44:35,020 DEBUG (0.001) SELECT `categories`.`id`, `categories`.`name` FROM `categories`; args=()
2021-07-29 01:44:38,864 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:44:38,865 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 2; args=(2,)
2021-07-29 01:44:38,867 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 7 LIMIT 1; args=(7,)
2021-07-29 01:44:38,868 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 8 LIMIT 1; args=(8,)
2021-07-29 01:44:38,870 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 9 LIMIT 1; args=(9,)
2021-07-29 01:44:38,871 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 10 LIMIT 1; args=(10,)
2021-07-29 01:44:38,873 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 11 LIMIT 1; args=(11,)
2021-07-29 01:44:38,874 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 12 LIMIT 1; args=(12,)
2021-07-29 01:44:38,876 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 13 LIMIT 1; args=(13,)
2021-07-29 01:44:38,877 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 14 LIMIT 1; args=(14,)
2021-07-29 01:44:38,879 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 15 LIMIT 1; args=(15,)
2021-07-29 01:44:38,880 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 16 LIMIT 1; args=(16,)
2021-07-29 01:44:38,882 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 17 LIMIT 1; args=(17,)
2021-07-29 01:44:47,494 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:44:47,495 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:44:47,496 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:44:47,498 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:44:47,499 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:44:47,501 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:44:47,502 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:44:47,504 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:45:20,436 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:45:20,437 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
Internal Server Error: /services/6
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
AttributeError: 'Service' object has no attribute 'exists'
2021-07-29 01:47:55,768 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:47:55,769 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:47:55,771 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:47:55,772 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:47:55,774 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:47:55,775 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:47:55,776 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:47:55,778 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:48:00,432 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:00,433 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 2; args=(2,)
2021-07-29 01:48:00,434 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 7 LIMIT 1; args=(7,)
2021-07-29 01:48:00,436 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 8 LIMIT 1; args=(8,)
2021-07-29 01:48:00,437 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 9 LIMIT 1; args=(9,)
2021-07-29 01:48:00,439 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 10 LIMIT 1; args=(10,)
2021-07-29 01:48:00,440 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 11 LIMIT 1; args=(11,)
2021-07-29 01:48:00,442 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 12 LIMIT 1; args=(12,)
2021-07-29 01:48:00,443 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 13 LIMIT 1; args=(13,)
2021-07-29 01:48:00,445 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 14 LIMIT 1; args=(14,)
2021-07-29 01:48:00,446 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 15 LIMIT 1; args=(15,)
2021-07-29 01:48:00,447 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 16 LIMIT 1; args=(16,)
2021-07-29 01:48:00,449 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 17 LIMIT 1; args=(17,)
2021-07-29 01:48:01,005 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:01,006 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:48:01,008 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:48:01,009 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:48:01,011 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:48:01,012 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:48:01,014 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:48:01,015 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:48:04,754 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:04,755 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 2; args=(2,)
2021-07-29 01:48:04,757 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 7 LIMIT 1; args=(7,)
2021-07-29 01:48:04,758 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 8 LIMIT 1; args=(8,)
2021-07-29 01:48:04,759 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 9 LIMIT 1; args=(9,)
2021-07-29 01:48:04,761 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 10 LIMIT 1; args=(10,)
2021-07-29 01:48:04,762 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 11 LIMIT 1; args=(11,)
2021-07-29 01:48:04,764 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 12 LIMIT 1; args=(12,)
2021-07-29 01:48:04,765 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 13 LIMIT 1; args=(13,)
2021-07-29 01:48:04,767 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 14 LIMIT 1; args=(14,)
2021-07-29 01:48:04,769 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 15 LIMIT 1; args=(15,)
2021-07-29 01:48:04,770 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 16 LIMIT 1; args=(16,)
2021-07-29 01:48:04,772 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 17 LIMIT 1; args=(17,)
2021-07-29 01:48:05,420 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:05,421 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 3; args=(3,)
2021-07-29 01:48:05,422 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 18 LIMIT 1; args=(18,)
2021-07-29 01:48:05,424 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 19 LIMIT 1; args=(19,)
2021-07-29 01:48:05,426 DEBUG (0.002) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 20 LIMIT 1; args=(20,)
2021-07-29 01:48:05,428 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 21 LIMIT 1; args=(21,)
2021-07-29 01:48:05,430 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 22 LIMIT 1; args=(22,)
2021-07-29 01:48:05,431 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 23 LIMIT 1; args=(23,)
2021-07-29 01:48:06,084 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:06,085 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 4; args=(4,)
2021-07-29 01:48:06,087 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 24 LIMIT 1; args=(24,)
2021-07-29 01:48:06,088 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 25 LIMIT 1; args=(25,)
2021-07-29 01:48:06,089 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 26 LIMIT 1; args=(26,)
2021-07-29 01:48:06,091 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 27 LIMIT 1; args=(27,)
2021-07-29 01:48:06,092 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 28 LIMIT 1; args=(28,)
2021-07-29 01:48:06,094 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 29 LIMIT 1; args=(29,)
2021-07-29 01:48:06,095 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 30 LIMIT 1; args=(30,)
2021-07-29 01:48:09,553 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:09,554 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:48:09,556 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:48:09,557 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:48:09,559 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:48:09,560 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:48:09,561 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:48:09,563 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:48:15,812 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:15,813 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
Internal Server Error: /services/1
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
AttributeError: 'Service' object has no attribute 'exists'
2021-07-29 01:48:16,815 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:48:16,816 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:48:16,817 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:48:16,819 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:48:16,820 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:48:16,821 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:48:16,823 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:48:16,824 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:49:01,233 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:49:01,234 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 3; args=(3,)
2021-07-29 01:49:01,236 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 18 LIMIT 1; args=(18,)
2021-07-29 01:49:01,238 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 19 LIMIT 1; args=(19,)
2021-07-29 01:49:01,239 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 20 LIMIT 1; args=(20,)
2021-07-29 01:49:01,240 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 21 LIMIT 1; args=(21,)
2021-07-29 01:49:01,242 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 22 LIMIT 1; args=(22,)
2021-07-29 01:49:01,243 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 23 LIMIT 1; args=(23,)
2021-07-29 01:49:01,790 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:49:01,791 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 3 LIMIT 21; args=(3,)
Internal Server Error: /services/3
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 35, in get
    if not Service.objects.get(id=service_id).exists():
AttributeError: 'Service' object has no attribute 'exists'
[2021-07-29 01:58:21 +0000] [22516] [INFO] Starting gunicorn 20.1.0
[2021-07-29 01:58:21 +0000] [22516] [INFO] Listening at: http://0.0.0.0:8000 (22516)
[2021-07-29 01:58:21 +0000] [22516] [INFO] Using worker: sync
[2021-07-29 01:58:21 +0000] [22517] [INFO] Booting worker with pid: 22517
2021-07-29 01:58:24,325 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 01:58:24,326 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:58:24,326 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 5 LIMIT 21; args=(5,)
2021-07-29 01:58:24,328 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 5; args=(5,)
2021-07-29 01:58:24,330 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 5; args=(5,)
2021-07-29 01:58:24,332 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 5; args=(5,)
2021-07-29 01:58:24,333 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 5; args=(5,)
2021-07-29 01:58:50,589 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:58:50,590 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:58:50,592 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:58:50,593 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:58:50,595 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:58:50,596 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:58:50,597 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:58:50,599 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:58:58,609 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:58:58,610 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 01:58:58,612 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 01:58:58,613 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 01:58:58,615 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 01:58:58,616 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 01:59:43,262 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:59:43,263 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 01:59:43,265 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 01:59:43,266 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 01:59:43,267 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 01:59:43,269 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 01:59:43,270 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 01:59:43,272 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 01:59:51,395 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:59:51,396 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 4 LIMIT 21; args=(4,)
2021-07-29 01:59:51,398 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 01:59:51,399 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 4; args=(4,)
2021-07-29 01:59:51,401 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 4; args=(4,)
2021-07-29 01:59:51,402 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 01:59:55,567 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 01:59:55,567 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 4 LIMIT 21; args=(4,)
2021-07-29 01:59:55,569 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 01:59:55,571 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 4; args=(4,)
2021-07-29 01:59:55,572 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 4; args=(4,)
2021-07-29 01:59:55,573 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 02:00:32,713 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:00:32,714 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 4 LIMIT 21; args=(4,)
2021-07-29 02:00:32,716 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 02:00:32,718 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 4; args=(4,)
2021-07-29 02:00:32,719 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 4; args=(4,)
2021-07-29 02:00:32,720 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
[2021-07-29 02:21:48 +0000] [23612] [INFO] Starting gunicorn 20.1.0
[2021-07-29 02:21:48 +0000] [23612] [INFO] Listening at: http://0.0.0.0:8000 (23612)
[2021-07-29 02:21:48 +0000] [23612] [INFO] Using worker: sync
[2021-07-29 02:21:48 +0000] [23613] [INFO] Booting worker with pid: 23613
2021-07-29 02:22:09,005 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 02:22:09,006 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:22:09,007 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:22:09,009 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:22:09,011 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:22:09,012 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:22:09,013 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:22:09,026 DEBUG (0.001) SELECT `reviews`.`id`, `reviews`.`created_at`, `reviews`.`updated_at`, `reviews`.`content`, `reviews`.`rating`, `reviews`.`user_id`, `reviews`.`master_id`, `reviews`.`service_id` FROM `reviews` WHERE `reviews`.`service_id` = 1 LIMIT 21; args=(1,)
Internal Server Error: /services/1
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 46, in get
    "image"         : Image.objects.get(service=service).image
NameError: name 'Image' is not defined
[2021-07-29 02:23:00 +0000] [23612] [INFO] Handling signal: term
[2021-07-29 02:23:00 +0000] [23613] [INFO] Worker exiting (pid: 23613)
[2021-07-29 02:23:00 +0000] [23612] [INFO] Shutting down: Master
[2021-07-29 02:23:53 +0000] [23681] [INFO] Starting gunicorn 20.1.0
[2021-07-29 02:23:53 +0000] [23681] [INFO] Listening at: http://0.0.0.0:8000 (23681)
[2021-07-29 02:23:53 +0000] [23681] [INFO] Using worker: sync
[2021-07-29 02:23:53 +0000] [23682] [INFO] Booting worker with pid: 23682
2021-07-29 02:23:55,467 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 02:23:55,468 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:23:55,469 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 4 LIMIT 21; args=(4,)
2021-07-29 02:23:55,471 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 02:23:55,473 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 4; args=(4,)
2021-07-29 02:23:55,475 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 4; args=(4,)
2021-07-29 02:23:55,476 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 4; args=(4,)
2021-07-29 02:23:55,477 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 21; args=(4,)
2021-07-29 02:23:57,260 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:23:57,261 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:23:57,262 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:23:57,264 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:23:57,265 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:23:57,267 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:23:57,268 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
[2021-07-29 02:39:06 +0000] [23929] [INFO] Starting gunicorn 20.1.0
[2021-07-29 02:39:06 +0000] [23929] [INFO] Listening at: http://0.0.0.0:8000 (23929)
[2021-07-29 02:39:06 +0000] [23929] [INFO] Using worker: sync
[2021-07-29 02:39:06 +0000] [23930] [INFO] Booting worker with pid: 23930
Internal Server Error: /applications/services/4/masters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 15, in wrapper
    payload         = jwt.decode(access_token, SECRET_KEY, ALGORITHM)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/jwt/api_jwt.py", line 106, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/jwt/api_jwt.py", line 142, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/jwt/api_jwt.py", line 177, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
2021-07-29 02:39:33,123 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 02:39:33,124 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:39:33,125 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'ecardenas@gmail.com' LIMIT 21; args=('ecardenas@gmail.com',)
2021-07-29 02:39:40,628 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:39:40,629 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 02:39:40,632 DEBUG (0.001) SELECT `applications`.`id`, `applications`.`created_at`, `applications`.`updated_at`, `applications`.`age`, `applications`.`region_id`, `applications`.`career`, `applications`.`gender`, `applications`.`user_id`, `applications`.`service_id`, `services`.`id`, `services`.`name`, `services`.`category_id` FROM `applications` INNER JOIN `services` ON (`applications`.`service_id` = `services`.`id`) WHERE (`applications`.`service_id` = 4 AND `applications`.`user_id` = 32) LIMIT 21; args=(4, 32)
2021-07-29 02:39:40,633 DEBUG (0.001) SELECT `regions`.`id`, `regions`.`name` FROM `regions` WHERE `regions`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 02:39:40,636 DEBUG (0.001) SELECT `masters`.`id`, `masters`.`created_at`, `masters`.`updated_at`, `masters`.`kakao_id`, `masters`.`certification`, `masters`.`business`, `masters`.`introduction`, `masters`.`description`, `masters`.`name`, `masters`.`phone`, `masters`.`password`, `masters`.`email`, `masters`.`gender`, `masters`.`birth`, `masters`.`region_id`, `masters`.`profile_image`, `masters`.`main_service_id`, `masters`.`career` FROM `masters` WHERE (`masters`.`main_service_id` = 4 AND `masters`.`gender` = 'female' AND `masters`.`region_id` = 3 AND `masters`.`birth` BETWEEN '2006-07-29' AND '2016-07-29' AND `masters`.`career` BETWEEN 5 AND 10); args=(4, 'female', 3, '2006-07-29', '2016-07-29', 5, 10)
2021-07-29 02:39:40,638 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 02:39:40,640 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 99; args=(99,)
2021-07-29 02:39:40,641 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
2021-07-29 02:39:40,642 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`master_id` = 511; args=(511,)
2021-07-29 02:39:52,724 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:39:52,725 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:39:52,727 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:39:52,728 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:39:52,729 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:39:52,731 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:39:52,732 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:39:52,734 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:39:54,823 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:39:54,827 DEBUG (0.004) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:39:54,829 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:39:54,831 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:39:54,832 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:39:54,834 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:39:54,835 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:39:56,565 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:39:56,566 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:39:56,568 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:39:56,569 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:39:56,571 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:39:56,572 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:39:56,573 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:39:56,575 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:40:07,943 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:40:07,944 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:40:07,946 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:40:07,947 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:40:07,949 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:40:07,950 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:40:07,952 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
Bad Request: /applications
2021-07-29 02:40:26,677 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:40:26,678 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:40:26,679 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:40:26,681 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:40:26,682 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:40:26,684 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:40:26,685 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:40:27,073 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:40:27,074 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:40:27,075 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:40:27,077 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:40:27,078 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:40:27,079 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:40:27,081 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:40:27,082 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:43:24,293 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:43:24,294 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:43:24,296 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:43:24,297 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:43:24,299 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:43:24,300 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:43:24,301 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:45:27,227 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:45:27,228 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:45:27,229 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:45:27,231 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:45:27,232 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:45:27,234 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:45:27,235 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:45:27,236 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:45:46,122 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:45:46,122 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 02:45:46,124 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:45:46,126 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 2; args=(2,)
2021-07-29 02:45:46,128 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 2; args=(2,)
2021-07-29 02:45:46,129 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:45:46,130 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 21; args=(2,)
Bad Request: /applications
2021-07-29 02:46:32,012 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:46:32,013 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 02:46:32,015 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:46:32,017 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 2; args=(2,)
2021-07-29 02:46:32,018 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 2; args=(2,)
2021-07-29 02:46:32,019 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:46:32,021 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 21; args=(2,)
Bad Request: /applications
2021-07-29 02:47:14,265 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:47:14,266 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 02:47:14,268 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:47:14,270 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 2; args=(2,)
2021-07-29 02:47:14,271 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 2; args=(2,)
2021-07-29 02:47:14,272 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:47:14,274 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 21; args=(2,)
2021-07-29 02:47:55,862 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:47:55,863 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:47:55,865 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:47:55,866 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:47:55,868 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:47:55,869 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:47:55,870 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:47:55,872 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:01,822 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:01,823 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:01,825 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:01,826 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:01,827 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:01,829 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:01,830 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:04,014 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:04,015 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:04,016 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:04,018 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:04,019 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:04,021 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:04,023 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:04,024 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:05,099 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:05,100 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:05,101 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:05,103 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:05,104 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:05,105 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:05,106 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:06,624 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:06,625 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:06,627 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:06,628 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:06,629 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:06,631 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:06,632 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:06,633 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:08,205 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:08,206 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:08,207 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:08,209 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:08,211 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:08,213 DEBUG (0.002) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:08,215 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:09,872 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:09,873 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:09,875 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:09,876 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:09,878 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:09,879 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:09,881 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:09,882 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:10,823 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:10,823 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:10,825 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:10,826 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:10,828 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:10,829 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:10,830 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:12,051 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:12,052 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:12,053 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:12,055 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:12,056 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:12,058 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:12,059 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:12,061 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:13,000 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:13,001 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:13,003 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:13,004 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:13,006 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:13,007 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:13,008 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:14,606 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:14,607 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:14,609 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:14,610 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:14,611 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:14,613 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:14,614 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:14,615 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:15,602 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:15,603 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:15,604 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:15,606 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 6; args=(6,)
2021-07-29 02:48:15,607 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 6; args=(6,)
2021-07-29 02:48:15,608 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 6; args=(6,)
2021-07-29 02:48:15,610 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 21; args=(6,)
2021-07-29 02:48:19,308 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:19,309 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:19,311 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:19,312 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:19,313 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:19,315 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:19,316 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:19,318 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:20,305 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:20,306 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 3; args=(3,)
2021-07-29 02:48:20,307 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 18 LIMIT 1; args=(18,)
2021-07-29 02:48:20,309 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 19 LIMIT 1; args=(19,)
2021-07-29 02:48:20,310 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 20 LIMIT 1; args=(20,)
2021-07-29 02:48:20,312 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 21 LIMIT 1; args=(21,)
2021-07-29 02:48:20,313 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 22 LIMIT 1; args=(22,)
2021-07-29 02:48:20,314 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 23 LIMIT 1; args=(23,)
2021-07-29 02:48:21,431 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:21,431 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 02:48:21,433 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 3; args=(3,)
2021-07-29 02:48:21,435 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 3; args=(3,)
2021-07-29 02:48:21,436 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 3; args=(3,)
2021-07-29 02:48:21,437 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 3; args=(3,)
2021-07-29 02:48:21,439 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 21; args=(3,)
2021-07-29 02:48:41,888 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:41,889 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:41,890 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:41,892 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:41,893 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:41,895 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:41,896 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:41,898 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:48:42,690 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:42,691 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:48:42,692 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:48:42,694 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:48:42,695 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:48:42,697 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:48:42,698 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:48:45,015 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:48:45,016 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:48:45,018 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:48:45,019 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:48:45,020 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:48:45,022 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:48:45,023 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:48:45,025 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:50:20,859 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:20,860 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:50:20,861 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:50:20,863 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:50:20,864 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:50:20,865 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:50:20,867 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:50:20,868 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:50:34,103 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:34,104 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:50:34,106 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:50:34,108 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:50:34,109 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:50:34,110 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:50:34,112 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:50:34,113 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:50:35,033 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:35,034 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:50:35,036 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:50:35,037 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:50:35,039 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:50:35,040 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:50:35,041 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:50:35,043 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:50:42,057 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:42,058 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE (`users`.`email` = 'jungzkxm@daum.net' AND `users`.`gender` = 'male' AND `users`.`kakao_id` = 1815246184 AND `users`.`name` = '성정준') LIMIT 21; args=('jungzkxm@daum.net', 'male', 1815246184, '성정준')
2021-07-29 02:50:42,061 DEBUG (0.001) INSERT INTO `users` (`created_at`, `updated_at`, `kakao_id`, `name`, `password`, `phone`, `gender`, `email`, `birth`) VALUES ('2021-07-29 02:50:42.060314', '2021-07-29 02:50:42.060361', 1815246184, '성정준', '', NULL, 'male', 'jungzkxm@daum.net', NULL); args=['2021-07-29 02:50:42.060314', '2021-07-29 02:50:42.060361', 1815246184, '성정준', '', None, 'male', 'jungzkxm@daum.net', None]
2021-07-29 02:50:44,242 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:44,243 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 3 LIMIT 21; args=(3,)
2021-07-29 02:50:44,245 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 3; args=(3,)
2021-07-29 02:50:44,246 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 3; args=(3,)
2021-07-29 02:50:44,248 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 3; args=(3,)
2021-07-29 02:50:44,249 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 3; args=(3,)
2021-07-29 02:50:44,250 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 21; args=(3,)
2021-07-29 02:50:45,387 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:50:45,388 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 02:50:45,390 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 02:50:45,391 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 02:50:45,393 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 02:50:45,394 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 02:50:45,397 DEBUG (0.002) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 02:50:45,398 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 02:51:54,287 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:51:54,288 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 2 LIMIT 21; args=(2,)
2021-07-29 02:51:54,290 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:51:54,292 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 2; args=(2,)
2021-07-29 02:51:54,293 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 2; args=(2,)
2021-07-29 02:51:54,294 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 2; args=(2,)
2021-07-29 02:51:54,296 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 21; args=(2,)
[2021-07-29 02:53:06 +0000] [23929] [INFO] Handling signal: term
[2021-07-29 02:53:06 +0000] [23930] [INFO] Worker exiting (pid: 23930)
[2021-07-29 02:53:06 +0000] [23929] [INFO] Shutting down: Master
[2021-07-29 02:53:12 +0000] [23977] [INFO] Starting gunicorn 20.1.0
[2021-07-29 02:53:12 +0000] [23977] [INFO] Listening at: http://0.0.0.0:8000 (23977)
[2021-07-29 02:53:12 +0000] [23977] [INFO] Using worker: sync
[2021-07-29 02:53:12 +0000] [23978] [INFO] Booting worker with pid: 23978
Internal Server Error: /applications/services/4/masters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/urls.py", line 3, in <module>
    from services.views import ServicesView, CategoryView
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 11, in <module>
    from core.views import users_signin_check
ImportError: cannot import name 'users_signin_check' from 'core.views' (/home/ubuntu/wecode/metgo_test/core/views.py)
Internal Server Error: /services/1
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/urls.py", line 3, in <module>
    from services.views import ServicesView, CategoryView
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 11, in <module>
    from core.views import users_signin_check
ImportError: cannot import name 'users_signin_check' from 'core.views' (/home/ubuntu/wecode/metgo_test/core/views.py)
Internal Server Error: /users/signin
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/urls.py", line 3, in <module>
    from services.views import ServicesView, CategoryView
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 11, in <module>
    from core.views import users_signin_check
ImportError: cannot import name 'users_signin_check' from 'core.views' (/home/ubuntu/wecode/metgo_test/core/views.py)
Internal Server Error: /users/signin
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/wecode/metgo_test/metGo/urls.py", line 3, in <module>
    from services.views import ServicesView, CategoryView
  File "/home/ubuntu/wecode/metgo_test/services/views.py", line 11, in <module>
    from core.views import users_signin_check
ImportError: cannot import name 'users_signin_check' from 'core.views' (/home/ubuntu/wecode/metgo_test/core/views.py)
[2021-07-29 02:55:39 +0000] [23977] [INFO] Handling signal: term
[2021-07-29 02:55:39 +0000] [23978] [INFO] Worker exiting (pid: 23978)
[2021-07-29 02:55:39 +0000] [23977] [INFO] Shutting down: Master
[2021-07-29 02:55:46 +0000] [24047] [INFO] Starting gunicorn 20.1.0
[2021-07-29 02:55:46 +0000] [24047] [INFO] Listening at: http://0.0.0.0:8000 (24047)
[2021-07-29 02:55:46 +0000] [24047] [INFO] Using worker: sync
[2021-07-29 02:55:46 +0000] [24048] [INFO] Booting worker with pid: 24048
2021-07-29 02:55:50,641 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 02:55:50,642 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:55:50,643 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'ecardenas@gmail.com' LIMIT 21; args=('ecardenas@gmail.com',)
2021-07-29 02:56:13,965 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 02:56:13,966 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
2021-07-29 02:56:13,968 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`id` = 1 LIMIT 21; args=(1,)
2021-07-29 02:56:13,970 DEBUG (0.001) SELECT AVG(`reviews`.`rating`) AS `average` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:56:13,971 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `masters` INNER JOIN `master_services` ON (`masters`.`id` = `master_services`.`master_id`) WHERE `master_services`.`service_id` = 1; args=(1,)
2021-07-29 02:56:13,973 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `applications` WHERE `applications`.`service_id` = 1; args=(1,)
2021-07-29 02:56:13,974 DEBUG (0.001) SELECT COUNT(*) AS `__count` FROM `reviews` WHERE `reviews`.`service_id` = 1; args=(1,)
2021-07-29 02:56:13,976 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 21; args=(1,)
[2021-07-29 03:00:49 +0000] [24047] [INFO] Handling signal: term
[2021-07-29 03:00:49 +0000] [24048] [INFO] Worker exiting (pid: 24048)
[2021-07-29 03:00:49 +0000] [24047] [INFO] Shutting down: Master
[2021-07-29 03:01:01 +0000] [24132] [INFO] Starting gunicorn 20.1.0
[2021-07-29 03:01:01 +0000] [24132] [INFO] Listening at: http://0.0.0.0:8000 (24132)
[2021-07-29 03:01:01 +0000] [24132] [INFO] Using worker: sync
[2021-07-29 03:01:01 +0000] [24133] [INFO] Booting worker with pid: 24133
2021-07-29 03:01:52,801 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 03:01:52,801 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:01:52,802 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
Internal Server Error: /users/matchingmasters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 18, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 48, in get
    data = json.loads(request.body)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-29 03:02:05,824 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:02:05,825 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`email` = 'ecardenas@gmail.com' LIMIT 21; args=('ecardenas@gmail.com',)
2021-07-29 03:02:14,652 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:02:14,653 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
Internal Server Error: /users/matchingmasters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 18, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 48, in get
    data = json.loads(request.body)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Bad Request: /services/2
2021-07-29 03:02:53,789 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:02:53,791 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 03:02:53,792 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 03:02:53,794 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 03:02:53,795 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 03:02:53,797 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 03:02:53,798 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 03:02:53,799 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 03:02:56,522 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:02:56,523 DEBUG (0.001) SELECT `services`.`id`, `services`.`name`, `services`.`category_id` FROM `services` WHERE `services`.`category_id` = 1; args=(1,)
2021-07-29 03:02:56,525 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 1 LIMIT 1; args=(1,)
2021-07-29 03:02:56,526 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 2 LIMIT 1; args=(2,)
2021-07-29 03:02:56,528 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 3 LIMIT 1; args=(3,)
2021-07-29 03:02:56,529 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 4 LIMIT 1; args=(4,)
2021-07-29 03:02:56,530 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 5 LIMIT 1; args=(5,)
2021-07-29 03:02:56,532 DEBUG (0.001) SELECT `images`.`id`, `images`.`image`, `images`.`service_id` FROM `images` WHERE `images`.`service_id` = 6 LIMIT 1; args=(6,)
2021-07-29 03:03:01,488 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:03:01,489 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE (`users`.`email` = 'jungzkxm@daum.net' AND `users`.`gender` = 'male' AND `users`.`kakao_id` = 1815246184 AND `users`.`name` = '성정준') LIMIT 21; args=('jungzkxm@daum.net', 'male', 1815246184, '성정준')
2021-07-29 03:05:04,899 DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:05:04,900 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
Internal Server Error: /users/matchingmasters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 18, in wrapper
    user            = User.objects.get(id=payload["id"])
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 48, in get
    data = json.loads(request.body)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-07-29 03:05:21 +0000] [24132] [INFO] Handling signal: term
[2021-07-29 03:05:21 +0000] [24133] [INFO] Worker exiting (pid: 24133)
[2021-07-29 03:05:22 +0000] [24132] [INFO] Shutting down: Master
[2021-07-29 03:22:05 +0000] [24625] [INFO] Starting gunicorn 20.1.0
[2021-07-29 03:22:05 +0000] [24625] [INFO] Listening at: http://0.0.0.0:8000 (24625)
[2021-07-29 03:22:05 +0000] [24625] [INFO] Using worker: sync
[2021-07-29 03:22:05 +0000] [24626] [INFO] Booting worker with pid: 24626
2021-07-29 03:22:27,980 DEBUG (0.001) 
                SELECT VERSION(),
                       @@sql_mode,
                       @@default_storage_engine,
                       @@sql_auto_is_null,
                       @@lower_case_table_names,
                       CONVERT_TZ('2001-01-01 01:00:00', 'UTC', 'UTC') IS NOT NULL
            ; args=None
2021-07-29 03:22:27,980 DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2021-07-29 03:22:27,981 DEBUG (0.001) SELECT `users`.`id`, `users`.`created_at`, `users`.`updated_at`, `users`.`kakao_id`, `users`.`name`, `users`.`password`, `users`.`phone`, `users`.`gender`, `users`.`email`, `users`.`birth` FROM `users` WHERE `users`.`id` = 32 LIMIT 21; args=(32,)
Internal Server Error: /users/matchingmasters
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/core/views.py", line 20, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/wecode/metgo_test/quotations/views.py", line 48, in get
    data = json.loads(request.body)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/project/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-07-29 03:23:57 +0000] [24625] [INFO] Handling signal: term
[2021-07-29 03:23:57 +0000] [24626] [INFO] Worker exiting (pid: 24626)
1
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MzIsImV4cCI6MTYyNzUzMTUzMH0.H43ShEBsoDFzUtnvwXCZ7Y9gixqiHx-W2dnGbfF6d4U
[2021-07-29 03:23:57 +0000] [24625] [INFO] Shutting down: Master
